# Generated by Django 3.2.10 on 2021-12-19 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('last_download', models.DateTimeField(verbose_name='Last Download')),
                ('download_count', models.BigIntegerField(default=0, verbose_name='Download Count')),
                ('Status', models.IntegerField(choices=[(0, 'public file'), (1, 'private file')], verbose_name='وضعیت')),
                ('size', models.FloatField(null=True, verbose_name='size')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
